version: 2.1

orbs:
  python: circleci/python@1.2.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          args: .
      - run: pip install '.[test]'
      - run: pytest
      - python/dist
      - store_artifacts:
          path: dist
      
workflows:
  main:
    jobs:
      - build-and-test
