version: 2.1

orbs:
  python: circleci/python@1.2.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          args: -e .

workflows:
  main:
    jobs:
      - build-and-test
